name: PHP Composer

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php2-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Enable problem matcher
      run: echo "::add-matcher::.github/phpmd-matcher.json"

    - name: Run PHPMD
      run: ./vendor/bin/phpmd . github codesize,controversial,design,naming,unusedcode --exclude 'vendor/*'
